server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vida_plus
    username: vida_user
    password: vida_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
